services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: transcendence_nginx
    environment:
      NGINX_SSL_PORT: "${NGINX_SSL_PORT:-8443}"
    ports:
      - "${NGINX_PORT:-8080}:80"
      - "${NGINX_SSL_PORT:-8443}:443"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
      - ./docker/nginx/html:/usr/share/nginx/html:ro
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge
